@server = http://localhost:4004
@me = Authorization: Basic {{$processEnv USER}}:
@basic = Authorization: Basic admin:admin


### ------------------------------------------------------------------------
### ------------------------------------------------------------------------
### ----------------------------CATALOG REST--------------------------------
### ------------------------------------------------------------------------
### ------------------------------------------------------------------------
### ------------------------------------------------------------------------
### ------------------------------------------------------------------------






### Create Cnh
POST  {{server}}/catalog-rest/Cnh
Accept: application/json
Content-Type: application/json

{ 
  "numeroRegistro": "7894900011530",
  "nome": "Et Bilu",
  "cpf": "22964328721",
  "docIdentidade": "25442123",
  "dataEmissao": "20240120",
  "dataValidade": "20240120",
  "contentURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAA1JREFUGFdjWNMW/R8ABfwCjc2t99UAAAAASUVORK5CYII=" 
}
     

### Read Cnh
GET {{server}}/catalog-rest/Cnh


### Read Cnh with filter
GET {{server}}/catalog/Cnh?filter=(substringof(%27Et%27,nome)%20or%20substringof(%Et%27,cpf))


### Read Cnh specific 
GET {{server}}/catalog-rest/Cnh/cf31b7df-51a6-47a2-a860-f6f0e1e1960e


### Read Binary
GET   {{server}}/catalog-rest/Cnh/cf31b7df-51a6-47a2-a860-f6f0e1e1960e/imageContent


### Create Cnh Image
POST  {{server}}/catalog-rest/postImageContent
Accept: application/json
Content-Type: application/json

{ 
  "ID": "cf31b7df-51a6-47a2-a860-f6f0e1e1960a",
  "contentURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAA1JREFUGFdjWNMW/R8ABfwCjc2t99UAAAAASUVORK5CYII="
}

### Delete Cnh 
DELETE {{server}}/catalog-rest/Cnh/5f12027a-6f6b-426a-ade9-3fc2a6388f18



### Delete Cnh Content
POST {{server}}/catalog-rest/Cnh/cf31b7df-51a6-47a2-a860-f6f0e1e1960e/deleteImageContent