@server = http://localhost:62462
@me = Authorization: Basic {{$processEnv USER}}:
@basic = Authorization: Basic admin:admin


### ------------------------------------------------------------------------
### ------------------------------------------------------------------------
### -------------------------------CATALOG----------------------------------
### ------------------------------------------------------------------------
### ------------------------------------------------------------------------




### Create Cnh
POST  {{server}}/odata/v4/catalog/Cnh
Accept: application/json
Content-Type: application/json

{ 

    "ID": "957a53fd-11a1-4c6c-804c-c956cb976f22"
  
}

### Read Cnh
GET {{server}}/odata/v4/catalog/Cnh



###  UPLOAD Cnh DMS
POST {{server}}/odata/v4/catalog/uploadcnhdms
Content-Type: application/json

{
 "folder": "spa-res:cmis:folderid:Ozbq2kvETi1CXFahZOmykRtjPlH_fLfauWNvZv_fGqY"
}


###  UPLOAD Cnh DMS
GET {{server}}/odata/v4/catalog/getURL()


### GET UPLOD URL EXTERNAL
GET https://sap-presales-brazil---btp-sap-presales-br-usa-dev-capdox-srv.cfapps.us10.hana.ondemand.com/odata/v4/catalog/getupurl(imagetype=%27image%2Fpng%27)


### Read Cnh with filter
GET {{server}}/odata/v4/catalog/Cnh?filter=(substringof(%27Et%27,nome)%20or%20substringof(%27Et%27,obs))

### Read Cnh specific 
GET {{server}}/odata/v4/catalog/Cnh(42e47c74-22a9-4c56-a60c-d234cefdc348)

### Read image Cnh specific 
GET {{server}}/odata/v4/catalog/Cnh(957a53fd-11a1-4c6c-804c-c956cb976f22)/imageContent



### Update Cnh
PATCH   {{server}}/odata/v4/catalog/Cnh(957a53fd-11a1-4c6c-804c-c956cb976f22)
Accept: application/json
Content-Type: application/json

{ 
  "obs": "Desc produto alterado"
}

### Upload Binary
PUT {{server}}/odata/v4/catalog/Cnh(957a53fd-11a1-4c6c-804c-c956cb976f22)/imageContent



< ./download.jpg




### Upload Binary
PUT {{server}}/odata/v4/catalog/Cnh/957a53fd-11a1-4c6c-804c-c956cb976f22/imageContent
Content-Type: image/png

< ./Test.png


### Upload Binary
    
PUT https://sap-presales-brazil---btp-sap-presales-br-usa-dev-capdox-srv.cfapps.us10.hana.ondemand.com/odata/v4/catalog/Cnh/c1514537-e5f1-492d-adf9-c70415f39d8a/imageContent   
#https://sap-presales-brazil---btp-sap-presales-br-usa-dev-capdox-srv.cfapps.us10.hana.ondemand.com/odata/v4/catalog/Cnh(cf31b7df-51a6-47a2-a860-f6f0e1e1960a)/imageContent
Content-Type: image/jpeg

< ./download.jpg


### Post Image Content
POST  {{server}}/odata/v4/catalog/postImageContent
Content-Type: image/jpeg

< ./download.jpg


### Delete Cnh Content
DELETE {{server}}/odata/v4/catalog/Cnh(957a53fd-11a1-4c6c-804c-c956cb976f22)/imageContent

### Delete Cnh 
DELETE {{server}}/odata/v4/catalog/Cnh(ea8c9918-dca5-419a-82cc-2e6f41ac4948)


### Delete Cnh 
DELETE {{server}}/odata/v4/catalog/Cnh(6fc2f475-530f-4d7d-9286-ad0ae4256dcc)
