@server = http://localhost:51105
@me = Authorization: Basic {{$processEnv USER}}:
@basic = Authorization: Basic admin:admin


### ------------------------------------------------------------------------
### ------------------------------------------------------------------------
### ----------------------------CATALOG REST--------------------------------
### ------------------------------------------------------------------------
### ------------------------------------------------------------------------
### ------------------------------------------------------------------------
### ------------------------------------------------------------------------






### Create Cnh
POST  {{server}}/rest/catalog-rest/Cnh
Accept: application/json
Content-Type: application/json

{ 
  "ID": "957a53fd-11a1-4c6c-804c-c956cb976f22"
}
     

### Read Cnh
GET {{server}}/rest/catalog-rest/Cnh


### Read Cnh with filter
GET {{server}}/rest/catalog-rest/Cnh?filter=(substringof(%27Et%27,nome)%20or%20substringof(%Et%27,OBS))


### Read Cnh specific 
GET {{server}}/rest/catalog-rest/Cnh/957a53fd-11a1-4c6c-804c-c956cb976f22


### Read Binary
GET   {{server}}/rest/catalog-rest/Cnh/957a53fd-11a1-4c6c-804c-c956cb976f22/imageContent


### Post Image content Create Cnh Image
POST  {{server}}/rest/catalog-rest/postImageContent
Accept: application/json
Content-Type: application/json

{ 
  "ID": "957a53fd-11a1-4c6c-804c-c956cb976f22",
  "contentURL": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAA1JREFUGFdjWNMW/R8ABfwCjc2t99UAAAAASUVORK5CYII="
}


### Upload Binary
PUT {{server}}/rest/catalog-rest/Cnh/957a53fd-11a1-4c6c-804c-c956cb976f22/imageContent
Content-Type: image/jpeg

< ./download.jpg


### Delete Cnh 
DELETE {{server}}/rest/catalog-rest/Cnh/957a53fd-11a1-4c6c-804c-c956cb976f22



### Delete Cnh Content
POST {{server}}/rest/catalog-rest/Cnh/957a53fd-11a1-4c6c-804c-c956cb976f22/deleteImageContent