@server = http://localhost:4004
@me = Authorization: Basic {{$processEnv USER}}:
@basic = Authorization: Basic admin:admin


### ------------------------------------------------------------------------
### ------------------------------------------------------------------------
### -------------------------------CATALOG----------------------------------
### ------------------------------------------------------------------------
### ------------------------------------------------------------------------




### Create Cnh
POST  {{server}}/odata/v4/catalog/Cnh
Accept: application/json
Content-Type: application/json

{ 
  "ID": "cf31b7df-51a6-47a2-a860-f6f0e1e1960a",
  "processID": "cf31b7df-51a6-47a2-a860-f6f0e1e1960a",
  "numeroRegistro": "7894900011532",
  "nome": "Et Bilu",
  "cpf": "22964328721",
  "docIdentidade": "25442123",
  "dataEmissao": "2024-01-20",
  "dataValidade": "2024-01-20",
  "obs": "Teste"
}

### Read Cnh
GET {{server}}/odata/v4/catalog/Cnh


### Read Cnh with filter
GET {{server}}/odata/v4/catalog/Cnh?filter=(substringof(%27Et%27,nome)%20or%20substringof(%27Et%27,obs))

### Read Cnh specific 
GET {{server}}/odata/v4/catalog/Cnh(cf31b7df-51a6-47a2-a860-f6f0e1e1960a)

### Read image Cnh specific 
GET {{server}}/odata/v4/catalog/Cnh(cf31b7df-51a6-47a2-a860-f6f0e1e1960a)/imageContent



### Update Cnh
PATCH   {{server}}/odata/v4/catalog/Cnh(cf31b7df-51a6-47a2-a860-f6f0e1e1960a)
Accept: application/json
Content-Type: application/json

{ 
  "obs": "Desc produto alteradoK"
}

### Upload Binary
PUT {{server}}/odata/v4/catalog/Cnh(cf31b7df-51a6-47a2-a860-f6f0e1e1960a)/imageContent
Content-Type: image/jpeg

< ./Test.jpg

### Upload Binary
PUT {{server}}/odata/v4/catalog/Cnh(cf31b7df-51a6-47a2-a860-f6f0e1e1960a)/imageContent
Content-Type: image/png

< ./Test.png


### Delete Cnh Content
DELETE {{server}}/odata/v4/catalog/Cnh(cf31b7df-51a6-47a2-a860-f6f0e1e1960a)/imageContent

### Delete Cnh 
DELETE {{server}}/odata/v4/catalog/Cnh(cf31b7df-51a6-47a2-a860-f6f0e1e1960a)


### Delete Cnh 
DELETE {{server}}/odata/v4/catalog/Cnh(f613edd1-49ae-4837-8fc2-f59834952017)
